In [2]:
# broadcasting
import numpy as np
a = np.arange(12).reshape((3,4))
b = np.arange(3).reshape(-1,1)
print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0]
 [1]
 [2]]


In [ ]:
a+b

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [ ]:
# np.where
np.where(a>3,90,0)

array([[ 0,  0,  0,  0],
       [90, 90, 90, 90],
       [90, 90, 90, 90]])

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.where(b>1)

(array([2]), array([0]))

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.where(a>2)

(array([0, 1, 1, 1, 1, 2, 2, 2, 2]), array([3, 0, 1, 2, 3, 0, 1, 2, 3]))

In [ ]:
# np.clip


In [ ]:
# np.histogram
marks = np.array([10, 20, 25, 30, 35, 40, 45, 50, 55, 60])

counts, bins = np.histogram(marks, bins=4)

print(counts)
print(bins)

[2 2 3 3]
[10.  22.5 35.  47.5 60. ]


In [ ]:
# np.isin

In [3]:
# np.isnan
arr = np.array([10, 20, 30, 40, 50])

result = np.isin(arr, [20, 40, 60])

print(result)
print(arr[result])

[False  True False  True False]
[20 40]


In [5]:
# np.percentile
marks = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(np.percentile(marks, 50))


55.0


In [6]:
np.percentile(marks, 25)
np.percentile(marks, 50)
np.percentile(marks, 75)

np.float64(77.5)